### ISSUE TITLE
Minimum version of poetry

### ISSUE THREAD

**Issue by chrisroadmap** [iiasa/emissions_harmonization_historical#2]
Consider updating README to include a note to upgrade `poetry` if errors occur. Running

    $ make virtual-environment

errors out with

    The Poetry configuration is invalid:
      - Additional properties are not allowed ('package-mode' was unexpected)

So then...

    $ pipx upgrade poetry

    upgraded package poetry from 1.7.1 to 1.8.3 (location: /Users/chris/.local/pipx/venvs/poetry)

and running the `make` command then works. There is some minimum version 1.7.1 < v <= 1.8.3 where this doesn't break.

**Comment by jkikstra** [comment]
Done; 15c7d54c34b7484e0e39c6e9fdc4137228f8f19a
